FROM python:3.10.13

RUN apt-get update && apt-get install -y curl git vim net-tools build-essential

RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg

RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list

RUN apt-get update && apt-get install -y git vim net-tools build-essential google-cloud-cli=500.0.0-0

WORKDIR /code

ENV PYTHONPATH=/code/src
ENV PORT 8080
